### ISSUE TITLE
[Bug] Upload not working in browser on PC

### ISSUE THREAD

**Issue by Matais1** [debkbanerji/lego-art-remix#108]
**Bug Description**
The site is not working

**To Reproduce**

1. Go to site
2. Try to upload an image
3. Does not finish uploading

**Comment by debkbanerji** [comment]
Hmmm... I haven't been able to reproduce this on Chrome or edge on PC.

Can you let me know which browser/OS you're using?

It would also be helpful if you can provide a screenshot that includes some console logs (from right click -> inspect -> console, at least on Chrome) to get an idea of what the issue could be.
