### ISSUE TITLE
Color palette request

### ISSUE THREAD

**Issue by ccwedin** [debkbanerji/lego-art-remix#13]
Hi, Deb! You've done a fantastic job with this!

I was wondering if you could add one more color to the palette: Very Light Gray, BrickLink ID 49. In 2003, Lego released 1x1 plates in that color for grayscale mosaics (i.e., "Mosaic Cat" https://www.bricklink.com/catalogItemInv.asp?S=k34431-1), and it'd be super helpful if that color could be added here.

Thanks so much!

**Comment by debkbanerji** [comment]
Thanks! The color was already present in the solid color reference list (bricklink-color.js) so it was fairly straightforward to add. I've pushed the newest version to prod so this is now available on the website.
