### ISSUE TITLE
"Select Input Image" button will not unlock

### ISSUE THREAD

**Issue by Shockbooms** [debkbanerji/lego-art-remix#15]
Hi, love your work, just wanted to report a bug. No matter how many times I refresh the page the "Select Input Image" button will not let me click. Usually when I come to the site, the button is 'locked' for a second or so (light green), and then turns dark green once it is ready to press. It does not turn dark green anymore, and I can no longer use the site on this computer. I tried clearing my cache and using a different browser. Just wanted to let you know. Again though, thank you for your website!

**Comment by debkbanerji** [comment]
That's odd - can you right click the page and click inspect to bring up the console logs and attach a screenshot?

Also, what version of the website are you using?

**Comment by debkbanerji** [comment]
(version can be found in the about section)

**Comment by Shockbooms** [comment]
version is v2020.12.24

**Comment by Shockbooms** [comment]
<img width="554" alt="Screen Shot 2020-12-25 at 9 34 01 PM" src="https://user-images.githubusercontent.com/60264118/103144547-35e60480-46f9-11eb-8725-eee14675aed6.png">

**Comment by Shockbooms** [comment]
here is the screenshot

**Comment by debkbanerji** [comment]
Try hard refreshing the page (ctrl+shift+r on most browsers) and see if that helps (the version should be updated). I pushed v2020.12.25 an hour or so ago so your browser could have a cached version of an old file. In the meantime, I'll look into adding a null check here to prevent issues in the event of further desyncs.

**Comment by Shockbooms** [comment]
Yep, this worked, thanks so much! You're the best :)

**Comment by debkbanerji** [comment]
No problem!! Thanks for letting me know about the issue. I've added in a dummy url parameter to the link to the JavaScript file which should keep things in sync for other users as well.
