### ISSUE TITLE
Export selected studs is not available now?

### ISSUE THREAD

**Issue by Joonho-cho** [debkbanerji/lego-art-remix#16]
Hi, Deb.

I'm big fan of your software.
There is something wrong to export selected studs function. Could you check?

**Comment by debkbanerji** [comment]
I'm having the same issue in prod. Thanks for the heads up. I'll look into this later today or tomorrow when I have time.

**Comment by debkbanerji** [comment]
Bug is fixed in `v2020.12.28` - closing
