### ISSUE TITLE
Question about color´s

### ISSUE THREAD

**Issue by Imperator-mm** [debkbanerji/lego-art-remix#19]
Hi,
Is it possible to use other colors than just the standard LEGO colors?
I have many other colors from China (that are not available from Lego) here but I don't know how I can incorporate them into Lego Art Remix.
Can I even use colors that are not supported by LEGO? Tried using a JSON editor but it doesn't seem to work.

Thanks in advance !

Markus

**Comment by debkbanerji** [comment]
It's built around hex codes so this shouldn't be too tricky to implement (what country the colors are from doesn't matter). It's a little work to implement but it should be doable maybe through a URL parameter with the extra colors.

**Comment by debkbanerji** [comment]
I've added in this feature in v2021.2.28. It's implemented using a url parameter with hex codes for your available colors. For example:

https://lego-art-remix.debkbanerji.com/?availableColors=#FF00FF,#333366

Just replace the hex codes with a comma separated list of your available colors.

**Comment by douglasblash** [comment]
Hi,

Yes, I tried this method with 3 nice new unique flesh-tone colors I got from a manufacturer in China.  It recognizes the custom colors added, but it just paints the whole image with only those 3 colors, and no others.  Is there an easy way to include all of the other standard Lego colors, or do I need to specify ALL of their hex values in the URL?

To double check, I also tried the test URL text you typed above.  The result is essentially the same, it just paints the whole thing with only those 2 new specified colors, and nothing else...!

Can you fix it?  Thanks!  =)

Doug

**Comment by debkbanerji** [comment]
Good call - fixed in v2022.4.23. It still defaults to only using selected colors, but you can still mix in bricklink colors. Let me know if something looks off.
