### ISSUE TITLE
browser issue

### ISSUE THREAD

**Issue by tpadev** [debkbanerji/lego-art-remix#20]
Is this app can only be open with safari browser ?, because I tried with chrome both desktop and mobile and firefox all the hyperlink can’t be opened. Inspect element shows error can’t find map or something.

**Comment by debkbanerji** [comment]
I'm having a little trouble replicating this - I've tried this on a few different devices (tried with chrome) and prod seems to work on both desktop on mobile. Can you attach a screenshot/video of the issue?

**Comment by tpadev** [comment]
Well somehow its working now, I still remember there are 2 errors when I tried to open the page previously.
Right now only one error and its working.
Thanks
![Screenshot 2021-02-22 160815](https://user-images.githubusercontent.com/69703841/108687350-34825e00-7529-11eb-8f46-2b2e22b80a8a.png)

**Comment by debkbanerji** [comment]
Interesting - I haven't updated anything recently so might just be a caching issue. The console message on the right is just a warning since the pixi library is looking for a source map that isn't provided (this is only needed for development so this is okay)
