### ISSUE TITLE
HSV slider tweak to enable fine tuning

### ISSUE THREAD

**Issue by RedEquinox** [debkbanerji/lego-art-remix#24]
![Untitled100](https://user-images.githubusercontent.com/83773677/117327790-e70c6080-ae8a-11eb-8704-87eba9198039.jpg)

Great site and algorithm! Have made many images with the site but would like to be able to tweak the HSV values with more precision if possible.

Is it possible to add + & - buttons to the end of each slider to enable fine tuning of the image. Mobile version of the site being used so it's difficult to amend values with any precision. See attached image as example. 

First time user to GitHub so apologies if I've posted this in the wrong place.

Many thanks

**Comment by debkbanerji** [comment]
Great suggestion - I've added this to v2021.5.6 so this should be in prod now.

**Comment by RedEquinox** [comment]
Wow! That was a quick fix! Thank you so much 😊👍 works great. Unfortunately when in a portrait orientation on my mobile the HSV sliders are now cut off (see attached screenshot - red highlighted section) displays fine when in landscape orientation however... 

![Untitled102](https://user-images.githubusercontent.com/83773677/117416513-5b89e280-af11-11eb-9313-c4c1503bab90.jpg)

Is it possible to cut out the section between step cells (highlighted green) down to zero when in portrait mode on mobile device?

Thanks for all your great work 😊

**Comment by debkbanerji** [comment]
Looks like this is because of a minimum width applied to the sliders by default - updated the CSS so this should be handled better.

**Comment by RedEquinox** [comment]
Works perfectly now! Thanks for the fix 👍😊
