### ISSUE TITLE
color conversion does not work correctly (BUG FOUND)

### ISSUE THREAD

**Issue by wierusna** [debkbanerji/lego-art-remix#42]
@debkbanerji Thank you for such a great project! 
I found a BUG:
When i try to make a mosaic out of 5 colors (gray-gradient) **Black, Dark bluish gray, Light gray, Very light bluish gray** and **white** with **64x64 resolution** and **1162pcs of each color** something goes wrong. It replaces black studs with white while there are darker colors availible. I totally understand that black color studs are missing BUT WHY it replaces it with white color studs and not darker (close to black) color studs?

Here are the screenshots:
1. https://ibb.co/Tr6Lx50
2. https://ibb.co/G7bG26y
3. https://ibb.co/kH7gVvW **(for better understanding, 80% of black and 20% of white)**

Sorry for my english =) and thank you for supporting such a great project! That is amazing!

**Comment by debkbanerji** [comment]
Good catch - seems to be an issue with the way color distances are compared in the event of a color running out. Should be fixed in v2021.7.4.
