### ISSUE TITLE
Browser issue

### ISSUE THREAD

**Issue by andrew-rob** [debkbanerji/lego-art-remix#43]
Tried in chrome and edge.  Similar to #20 I can't click any of the buttons after uploading an image. First time I have used the app so not a caching issue.

![image](https://user-images.githubusercontent.com/47648546/124536761-e6c51d00-de5b-11eb-8b14-f0f07cae4a8f.png)

**Comment by debkbanerji** [comment]
Hmm... looks like an issue loading in the jquery file - might be a problem with their CDN or the connection being reset before jquery could load in. Are you able to load https://code.jquery.com/jquery-3.2.1.slim.min.js in on your browser? After checking, can you hard reload and see if the same issue shows up in the console?

**Comment by andrew-rob** [comment]
So here: 
![image](https://user-images.githubusercontent.com/47648546/124537605-8fc04780-de5d-11eb-8421-16153613b5e0.png)
doesn't load unless I hard refresh.  
![image](https://user-images.githubusercontent.com/47648546/124537684-b67e7e00-de5d-11eb-9d29-73842645a342.png)

The lego art remix still has the same errors in the console after a hard reload.
![image](https://user-images.githubusercontent.com/47648546/124537716-c8602100-de5d-11eb-9bea-c9bfa5708661.png)

**Comment by andrew-rob** [comment]
Working in chrome after a hard refresh in the lego art remix.

**Comment by debkbanerji** [comment]
Interesting - the fact that it wasn't working onEdge  until a hard refresh means that it was probably due to an issue with jQuery's CDN or your internet. Clearing the browser cache on Edge might resolve the issue, since it looks like Edge may still think the file isn't available from that page.

**Comment by debkbanerji** [comment]
Closing for now since this is JQuery CDN related.
