### ISSUE TITLE
Use symbols in instructions instead of numbers

### ISSUE THREAD

**Issue by enfact83** [debkbanerji/lego-art-remix#44]
I'd like to suggest the option to use symbols or emojis instead of numbers in the instructions. Some people find the numbers abit confusing. It will be great for younger or older persons who has difficulty recognising the numbers.

**Comment by wierusna** [comment]
Good idea! Like this with emojis!

**Comment by debkbanerji** [comment]
Closing for now in favor of https://github.com/debkbanerji/lego-art-remix/issues/74. Feel free to reopen if you feel this would still be helpful.
