### ISSUE TITLE
Light Nougat as 1x1 square plate

### ISSUE THREAD

**Issue by DutchHoodedOne** [debkbanerji/lego-art-remix#54]
I noticed that the new 1x1 square plate in Light Nougat  is not supported. Although I have the Light Nougat color in the available color list. When I change the pixel type to 1x1 square , it’s not using this color.

**Comment by debkbanerji** [comment]
Available colors are read independently of pixel piece type. It's likely that the closest color for the selected pixel just wasn't light nougat. Feel free to reopen the issue if this isn't the case.
