### ISSUE TITLE
Vibrant Yellow

### ISSUE THREAD

**Issue by debkbanerji** [debkbanerji/lego-art-remix#65]
Add this in if pixels are available in this new color. It seems to be tracked on brickset but may not be in bricklink's system yet.

**Comment by douglasblash** [comment]
Oh, connecting back to what I was saying before, I see that the RGB value for "vibrant yellow" is (255, 252, 0).  So you see that it maxes-out the red channel, and it almost maxes-out the green channel too.  So it actually reflects more red wavelengths than that in real life, but the maximum reading possible is just 255 max.  And the RGB value for "vibrant coral" is (255, 129, 114), so it's a similar case...  It maxes-out the red channel.  

And I think that's the exact reason why they uniquely label these two colors as being the "vibrant" ones.  It indicates a color that overruns one or more of the RGB channels, so it can't be displayed on a computer monitor with its true full intensity, as it appears in the real plastic.

On a different note, if they label a color as "medium", I think that means that its overall lightness is close to the 50% point on the gray-scale, or "medium luminosity".

And finally, if they call a color "bright", that definitely seems to mean that it is "high saturation", not always necessarily high luminosity.

Hmm, so there is definitely a scientific and logical basis for the official Lego color names, although they can seem confusing at first!  =)

**Comment by debkbanerji** [comment]
Bricklink is seemingly calling this 'Neon Yellow' - added in v2022.7.9
