### ISSUE TITLE
[Uncaught ReferenceError: Cropper is not defined]

### ISSUE THREAD

**Issue by TurboTu** [debkbanerji/lego-art-remix#66]
Caught "Uncaught ReferenceError: Cropper is not defined" error
When I follow the steps in build-service-worker.js, the cdn js file cropper.min.js and cropper.min.css can not access, so I replace all cdn js into local js files like “<script src="js/cropper.min.js" crossorigin="anonymous" referrerpolicy="no-referrer"></script>“
and then rebuild again，when I open the web page and upload my image，the  "Uncaught ReferenceError: Cropper is not defined" error happened

**Comment by debkbanerji** [comment]
What changes did you make to the index file? Did the cropper JavaScript load in correctly and did it load in before the files in which it's used?

**Comment by debkbanerji** [comment]
No response, so closing for now. Feel free to reopen if the issue persists.
