### ISSUE TITLE
[Feature Request] Allow selecting multiple sets for Input Pieces

### ISSUE THREAD

**Issue by cmccandless** [debkbanerji/lego-art-remix#70]
**Is your feature request related to a problem? If so, please describe it.**
Before selecting an input image, there is a dropdown to select the Input Pieces. I can select one existing set as my "palette", but it would be nice if I could select multiple (i.e. select both 31199 Iron Man and 31200 The Sith).

**Comment by debkbanerji** [comment]
Try the "Mix in Studs From Existing Set" option under "Available Colors" in step 3. Feel free to reopen if this doesn't address your use case.

**Comment by cmccandless** [comment]
That does it, thanks!

**Comment by b321gonzo** [comment]
If this could be revisited that would be great. Currently when I mix in studs I have to select the the Extra Dots Series individually 5 to 8 times each on top of all the other sets I need to input individually
