### ISSUE TITLE
Correct RGB values for flesh colors - NEW official 2022 "medium brown", also "nougat" and "medium nougat"

### ISSUE THREAD

**Issue by douglasblash** [debkbanerji/lego-art-remix#71]
**Bug Description**

It looks like some of the flesh tones may have incorrect RGB values, so they are placed incorrectly in the art.  Some of those RGB values may have already been fixed or updated in the BrickLink database just recently.  Please verify:
1) nougat
2) medium nougat
3) medium brown - This is a new official Lego color for 2022.  It is a new shade of flesh tone, falling between medium nougat and reddish brown on the scale.  It looks as though BrickLink has corrected their RGB value for it recently, although some of the photos may still seem too dark.

https://www.bricklink.com/catalogColors.asp
https://www.bricklink.com/catalogList.asp?catType=P&colorPart=28
https://www.bricklink.com/catalogList.asp?catType=P&colorPart=150
https://www.bricklink.com/catalogList.asp?catType=P&colorPart=240

Thanks!  =)

**Comment by debkbanerji** [comment]
Nice catch! Updated in v2022.3.24 based on Bricklink's color guide.  The hex codes for nougat (#ffaf7d) and medium nougat (#e3a05b) seem to be fine, so I've left them unchanged. Feel free to reopen if I missed something.
