### ISSUE TITLE
Larger sizes dont appear on site and wont generate instructions

### ISSUE THREAD

**Issue by mbassalbioinformatics** [debkbanerji/lego-art-remix#73]
**Bug Description**
For some reason when ive tried on 2 machines now, when i try to increase the size of the generation beyond 64 studs, it refuses to show up in the 4th and final panel. It seems for a number of different stud size images the first 3 panels will show fine, but the 4th seems to get stuck. When it does so, even the generate instructions wont work so cant even force it to see how it will show.

**To Reproduce**
Try to input image onto site and change the size larger than 64*64 studs. The first 3 panels will show but the 4th refuses to show up. Ive attached a screenshot to show what i mean.

**Expected behavior**
Would expect that the site to generate the final export.

![Screenshot 2022-04-24 232505](https://user-images.githubusercontent.com/42388216/164979929-032fa6ef-3dc7-44e0-82c1-51d495d76cb3.png)

**Comment by debkbanerji** [comment]
How many pieces show up under 'Available Colors' in step 3? If you don't have enough pieces, step 4 cannot run. I'll look into updating the UI to correctly convey this.

**Comment by debkbanerji** [comment]
Added a UI explanation in v2022.4.24. Feel free to reopen the issue if something still looks off.
