### ISSUE TITLE
[Feature Request] New color : nougat

### ISSUE THREAD

**Issue by Tats92** [debkbanerji/lego-art-remix#78]
In the Lego set 31204 (Elvis Presley), a new color appeared for 1x1 round tiles : "nougat" (something between "light nougat" and "medium nougat").
But in Lego Art Remix, it's not available. I think it's an excellent color for improving portraits.
Can it be added ?

**Comment by Tats92** [comment]
I just discovered I can manually add a new color !
That's perfect.

**Comment by debkbanerji** [comment]
Sweet - where did this color not show up where you'd initially expect it to?

**Comment by Tats92** [comment]
On step 3 : "Available colors", when using 1x1 tiles. On the default list of colors, "nougat" is missing. But I can add it by using "+ Add Stud".

**Comment by debkbanerji** [comment]
Got it. Should show up as a default as of v2022.7.1
