### ISSUE TITLE
Still not able to add in custom colors (non-Lego colors)

### ISSUE THREAD

**Issue by douglasblash** [debkbanerji/lego-art-remix#80]
Hi, I used the link you gave to add in custom colors, but as before, if just paints the entire image with just those two new colors (fuchsia and navy).

As a quick work-around, could we just create a link that includes all the hex-codes for the standard Lego colors, then anyone could add more hex-codes to it?

Oh, and do you have a list of the hex-codes (or else the RGB-codes) for all the standard Lego colors?  I could generate one myself, but maybe you have one you can post... 

Thanks, man!  =)

Doug

**Comment by debkbanerji** [comment]
The fix to this is to go to step 3 and mix in all the supported colors (so in addition to the custom colors from the url you have all the colors supported by the application)
