### ISSUE TITLE
[Bug] Incorrect value for Dark brown color pieces in the "Star wars" set

### ISSUE THREAD

**Issue by alexey2020** [debkbanerji/lego-art-remix#98]
**Bug Description**
Incorrect value for Dark brown color pieces in the "Star wars" set

**To Reproduce**

1. Select "Star wars" set
2. Check the number of Dark Brown pieces
3. It's 100

**Expected behavior**
Should be 200

**Screenshots/Video**

![photo_2022-12-11_22-59-16](https://user-images.githubusercontent.com/13920980/206931654-0965ec22-f4a9-4417-8075-9b8b8a675361.jpg)
![photo_2022-12-11_22-59-18](https://user-images.githubusercontent.com/13920980/206931655-1b9f2057-7563-4f4f-a882-23a34cb3870a.jpg)

**Additional context**
Thank you for the beautiful service!
![jim](https://user-images.githubusercontent.com/13920980/206931605-4ce5e47b-5a83-4d11-92c9-41e7fd271c33.jpg)

**Comment by debkbanerji** [comment]
Good catch! Should be fixed in v2022.12.11 - thanks for submitting this
