### ISSUE TITLE
I need help with the instructions

### ISSUE THREAD

**Issue by Kal666** [debkbanerji/lego-art-remix#99]
I am making a 144 x 144 mosaic.  When i open the instructions .pdf, the instructions are for a 16 x 16 base plate.  I am using 48 x 48 plates.  Since the instructions are for the 16 x 16 plates do i start in the top left corner for the first section, then go from left to right, top to bottom for each 16 x 16 picture in the instructions?

**Comment by debkbanerji** [comment]
Thanks for opening the issue! The instructions should generate pages starting from the top left. The first page should also have a guide to what plates go where if you need to make sure. Let me know if you have any other issues!
